// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0qtbEEL4itE2xXion2aWRd9brwols5I',
    appId: '1:18372020496:web:bb5a2f6062f1d9a41bfd95',
    messagingSenderId: '18372020496',
    projectId: 'flash-meet-app',
    authDomain: 'flash-meet-app.firebaseapp.com',
    storageBucket: 'flash-meet-app.firebasestorage.app',
    measurementId: 'G-Y4483ED6PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg1bXtdT1at1wy8lB3TvPcn2x6-HphDps',
    appId: '1:18372020496:android:c2effc060d6f386c1bfd95',
    messagingSenderId: '18372020496',
    projectId: 'flash-meet-app',
    storageBucket: 'flash-meet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDupU4j0Y97Vee9CjdjcqNMEynezw8-4MI',
    appId: '1:18372020496:ios:c390aba477c8cb5b1bfd95',
    messagingSenderId: '18372020496',
    projectId: 'flash-meet-app',
    storageBucket: 'flash-meet-app.firebasestorage.app',
    iosClientId: '18372020496-qa4d9i12d963ukji168fv7b08krdh1ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashMeetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDupU4j0Y97Vee9CjdjcqNMEynezw8-4MI',
    appId: '1:18372020496:ios:c390aba477c8cb5b1bfd95',
    messagingSenderId: '18372020496',
    projectId: 'flash-meet-app',
    storageBucket: 'flash-meet-app.firebasestorage.app',
    iosClientId: '18372020496-qa4d9i12d963ukji168fv7b08krdh1ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashMeetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT0qtbEEL4itE2xXion2aWRd9brwols5I',
    appId: '1:18372020496:web:641350041012db511bfd95',
    messagingSenderId: '18372020496',
    projectId: 'flash-meet-app',
    authDomain: 'flash-meet-app.firebaseapp.com',
    storageBucket: 'flash-meet-app.firebasestorage.app',
    measurementId: 'G-03Q5E2P578',
  );
}
